apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "assign-roles-permissions.fullname" . }}
  labels:
    app: {{ template "assign-roles-permissions.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      name: {{ template "assign-roles-permissions.fullname" . }}
      labels:
        release: {{ .Release.Name }}
        app: {{ template "assign-roles-permissions.name" . }}
    spec:
      containers:
      - name: {{ template "assign-roles-permissions.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        args: [
            "assign-roles-permissions", 
            "--host",
            "$(USER_API_SERVICE_HOST)",
            "--port",
            "$(USER_API_SERVICE_PORT)",
            "--phost",
            "$(PERMISSION_API_SERVICE_HOST)",
            "--pport",
            "$(PERMISSION_API_SERVICE_PORT)",
            "--rhost",
            "$(ROLE_API_SERVICE_HOST)",
            "--rport",
            "$(ROLE_API_SERVICE_PORT)",
            "--config",
            "/etc/configfile/user.config"
            ]
        volumeMounts:
          - name: config
            mountPath: "/etc/configfile"
            readOnly: true
      volumes:
        - name: config
          secret:
            secretName: {{ template "assign-roles-permissions.name" . }}
      restartPolicy: Never

