users:
  - email: crossthebreeze@gmail.com
    role:
      name: test
      description: A role with superpower
      permission:
        name: admin2
        resource: dictybase
        description: A permission with administration access
